name: 🧪 Functional Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  functional-linux:
    name: Functional Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macos11]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Functional Tests
        run: |
          chmod +x run.sh
          bash run.sh ${{matrix.os}}
        working-directory: v2/cmd/functional-test
